### ISSUE TITLE
No MAY-level requirements

### ISSUE THREAD

**Issue by paulehoffman** [marcblanchet/rfc7720bis#3]
In -00, it says "*  MAY support validating Message Digests for DNS Zones [RFC8976]." MAY-level requirements are not requirements, and there are probably dozens that one can think of. This should be removed.

**Comment by hardaker** [comment]
I disagree with the notion that we SHOULD NOT include MAYs.  But since I think the consensus was to not require ZONEMD at all at this point, the MAY will be dropped anyway.  Thus removed in 46561a5.  If we do want to insert optional requirements to better document what the RSOs MAY support, we can change the text that currently says "requirements" at the same time to better clarify the intent of the document.
